### file generated by plotpy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as tck
import matplotlib.patches as pat
import matplotlib.path as pth
import matplotlib.patheffects as pff
import matplotlib.lines as lns
import matplotlib.transforms as tra
import mpl_toolkits.mplot3d as m3d
NaN = np.NaN
EXTRA_ARTISTS = []
def add_to_ea(obj):
    if obj!=None: EXTRA_ARTISTS.append(obj)
COLORMAPS = [plt.cm.bwr, plt.cm.RdBu, plt.cm.hsv, plt.cm.jet, plt.cm.terrain, plt.cm.pink, plt.cm.Greys]
def get_colormap(idx): return COLORMAPS[idx % len(COLORMAPS)]
AX3D = None
def maybe_create_ax3d():
    global AX3D
    if AX3D == None:
        AX3D = plt.gcf().add_subplot(111, projection='3d')
        AX3D.set_xlabel('x')
        AX3D.set_ylabel('y')
        AX3D.set_zlabel('z')
        add_to_ea(AX3D)
def data_to_axis(coords):
    plt.axis() # must call this first
    return plt.gca().transLimits.transform(coords)
def axis_to_data(coords):
    plt.axis() # must call this first
    return plt.gca().transLimits.inverted().transform(coords)
def set_equal_axes():
    ax = plt.gca()
    if AX3D == None:
        ax.axes.set_aspect('equal')
        return
    try:
        ax.set_box_aspect([1,1,1])
        limits = np.array([ax.get_xlim3d(), ax.get_ylim3d(), ax.get_zlim3d()])
        origin = np.mean(limits, axis=1)
        radius = 0.5 * np.max(np.abs(limits[:, 1] - limits[:, 0]))
        x, y, z = origin
        ax.set_xlim3d([x - radius, x + radius])
        ax.set_ylim3d([y - radius, y + radius])
        ax.set_zlim3d([z - radius, z + radius])
    except:
        import matplotlib
        print('VERSION of MATPLOTLIB = {}'.format(matplotlib.__version__))
        print('ERROR: set_box_aspect is missing in this version of Matplotlib')
x=np.array([5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,],dtype=float)
y=np.array([0.30283427238464355,0.5330073833465576,0.7986268997192383,1.0692846775054932,1.286877155303955,1.5224871635437012,1.8031561374664307,2.0303425788879395,2.3067824840545654,2.618229389190674,2.8433303833007813,3.1177589893341064,3.371561288833618,3.640733003616333,3.8751988410949707,4.128981590270996,4.425241470336914,4.695688247680664,5.260429859161377,5.347133636474609,],dtype=float)
plt.plot(x,y,label='Python',alpha=0.8,color='#4A6DBD',linestyle='-')
x=np.array([5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,],dtype=float)
y=np.array([0.335,0.492,0.737,0.973,1.181,1.391,1.639,1.857,2.096,2.336,2.567,2.801,3.033,3.259,3.498,3.74,3.953,4.183,4.448,4.839,],dtype=float)
plt.plot(x,y,label='Rust',alpha=0.8,color='#FF6318',linestyle='-')
plt.xlabel(r'Number of New Tokens Generated')
plt.ylabel(r'Time [seconds]')
plt.title(r'Speed of Generating Tokens in Rust vs Python')
h,l=plt.gca().get_legend_handles_labels()
if len(h)>0 and len(l)>0:
    leg=plt.legend(handlelength=3,ncol=1,loc='best')
    add_to_ea(leg)

fn=r'Rust_v_Python.pdf'
plt.savefig(fn,bbox_inches='tight',bbox_extra_artists=EXTRA_ARTISTS)
